name: jupyter-keras-gpu
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5
    - scikit-learn==0.19.1
    - bazel
    - cython
    - openblas
    - numpy
    - matplotlib
    - bokeh
    - opencv3
    - pillow
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio
    - nltk
    - gensim
    - pip:
        - jupyter
        - moviepy
        - tensorflow-gpu==1.0.0
        - pydot
        - pandas-gbq
        - awscli
